// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

const mongoose = require("mongoose");
describe('Database Connection', () => {
  beforeAll(async () => {
    await mongoose.disconnect();
  });

  test('should connect to database successfully', async () => {
    await mongoose.connect('mongodb://127.0.0.1:27017', { dbName: 'backend' });
    const db = mongoose.connection;
    expect(db.readyState).toBe(1);
  });

  test('should fail to connect to database', async () => {
    await mongoose.connect('mongodb://127.0.0.1:27018', { dbName: 'backend' })
      .catch(e => {
        expect(e).toBeInstanceOf(mongoose.Error);
      });
  });

  afterAll(async () => {
    await mongoose.disconnect();
  });
});
