// ********RoostGPT********
// Test generated by RoostGPT for test aman12Feb using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

let mongoServer;
const opts = { useUnifiedTopology: true, useNewUrlParser: true };

// Jest hooks to set up and tear down MongoDB Memory Server
beforeAll(async () => {
  mongoServer = new MongoMemoryServer();
  const mongoUri = await mongoServer.getUri();
  await mongoose.connect(mongoUri, opts, (err) => {
    if (err) console.error(err);
  });
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

describe('MongoDB Connection', () => {
  test('should connect to in-memory MongoDB', async () => {
    const isConnected = mongoose.connection.readyState;
    expect(isConnected).toBe(1);
  });

  test('should disconnect from in-memory MongoDB', async () => {
    await mongoose.disconnect();
    const isDisconnected = mongoose.connection.readyState;
    expect(isDisconnected).toBe(0);
  });
});
