// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

import express from "express";
import path from "path";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt"; 

describe("Database Connection", () => {
  let connection;
  let db;

  beforeAll(async () => {
    connection = await mongoose.connect("mongodb://127.0.0.1:27017", {dbName: "backend"});
    db = mongoose.connection;
  });

  afterAll(async () => {
    await connection.close();
    await db.close();
  });

  test("should establish a connection to the database", async () => {
    const openSpy = jest.spyOn(mongoose, 'connect');
    await mongoose.connect("mongodb://127.0.0.1:27017", {dbName: "backend"});
    expect(openSpy).toHaveBeenCalled();
  });

  test("should have a database instance", () => {
    expect(db).toBeDefined();
  });
});
