// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

import mongoose from 'mongoose';

describe('Database Connection', () => {
  let connection;
  
  beforeAll(async () => {
    connection = await mongoose.connect("mongodb://127.0.0.1:27017", {
      dbName: "backend"
    });
  });

  test('should connect to database successfully', () => {
    expect(connection.connections[0].readyState).toBe(1);
  });

  test('should have the correct database name', () => {
    expect(connection.connections[0].name).toBe('backend');
  });

  afterAll(async () => {
    await mongoose.connection.close();
  });
});
