// Install jest and supertest first using npm
// npm install --save-dev jest supertest

// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

import express from "express";
import path from "path";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";
import request from "supertest";

const app = express();
app.listen(5000, () => {
  console.log("Server is working");
})

describe("Server Test Suite", () => {
  let server;

  beforeAll(() => {
    server = app.listen(5000);
  });

  afterAll((done) => {
    server.close(done);
  });

  test("should start the server", async () => {
    const response = await request(server).get("/");
    expect(response.status).toBe(200);
  });

  test("should fail when invalid path is provided", async () => {
    const response = await request(server).get("/invalidPath");
    expect(response.status).toBe(404);
  });
});

