// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

import request from 'supertest';
import express from 'express';
import path from 'path';
import mongoose from 'mongoose';
import cookieParser from 'cookie-parser';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';

// Import the server
import app from './index';

// Test suite
describe('Testing server functionality', () => {
  let server;

  // Start server before each test
  beforeEach((done) => {
    server = app.listen(5000, () => {
      global.agent = request.agent(server);
      done();
    });
  });

  // Close server after each test
  afterEach((done) => {
    return server && server.close(done);
  });

  // Test case 1: Server is able to start
  test('Server starts correctly', async () => {
    const response = await request(app).get('/');
    expect(response.status).toBe(200);
  });

  // Test case 2: Server returns error for unknown route
  test('Server returns 404 for unknown route', async () => {
    const response = await request(app).get('/unknown-route');
    expect(response.status).toBe(404);
  });
});
