// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

import express from "express";
import path from "path";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";
import request from 'supertest';
import app from './index.js';

jest.mock('./isAuthenticated', () => {
  return (req, res, next) => {
    req.user = { name: 'Test User' };
    next();
  };
});

describe('GET /', () => {
  test('should return 200 and render view with user name', async () => {
    const res = await request(app).get('/');
    expect(res.status).toBe(200);
    expect(res.text).toContain('Test User');
  });

  test('should return 500 when there is an error', async () => {
    jest.mock('./isAuthenticated', () => {
      return (req, res, next) => {
        next(new Error('Mock error'));
      };
    });
    const res = await request(app).get('/');
    expect(res.status).toBe(500);
  });
});

