// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

import express from "express";
import path from "path";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";
import request from "supertest";
import app from "./index";

jest.mock('jsonwebtoken', () => ({
  verify: jest.fn().mockImplementation((token, secret, callback) => {
    callback(false, { name: 'Test User' });
  })
}));

describe("GET / - Homepage", () => {
  test("Should respond with a 200 status code", async () => {
    const response = await request(app).get("/");
    expect(response.statusCode).toBe(200);
  });

  test("Should render 'logout' view with user name", async () => {
    const response = await request(app).get("/");
    expect(response.text).toContain('Test User');
  });

  test("Should respond with a 401 status code if not authenticated", async () => {
    jwt.verify.mockImplementationOnce((token, secret, callback) => {
      callback(true);
    });
    const response = await request(app).get("/");
    expect(response.statusCode).toBe(401);
  });
});
