// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

const { generateLovePercent } = require('./features');


describe('generateLovePercent method', () => {
  test('should return a string', () => {
    expect(typeof generateLovePercent()).toBe('string');
  });

  test('should return a percentage', () => {
    expect(generateLovePercent()).toMatch(/^[0-9]{1,3}%$/);
  });

  test('should not exceed 100%', () => {
    const result = generateLovePercent();
    const percent = parseInt(result.slice(0, -1));
    expect(percent).toBeLessThanOrEqual(100);
  });
});
